### ISSUE TITLE
"Building Pattern Library..."

### ISSUE THREAD

**Issue by sethwhitaker** [NoDivide/astrum#27]
First off, Love this project! Very simple, cant wait to see what you guys have in store.

Had a question about the loading/building.

In my local setup, I have significantly reduced the `timeouts` set during the page loading process in `app/main.js` because I was getting a bit annoyed at waiting 2 seconds for every refresh.

Is there a downside to this while the components are loaded? So far I haven't seen any issues, but I also don't have many components set up in there yet.

Appreciate any feedback!
Best

**Comment by RyanHavoc** [comment]
Hi Seth,

With regards to the resizing we're going to phase that out. The original design for Astrum was quite different and at the time we decided to mask the transition between breakpoints while the interface adjusted itself because things were looking broken. This is no longer the case but the resizer is still in there waiting to be removed.

With regards to the load time Astrum detects when components are visible a certain resolutions based on their height on load. He can't detect this until all the components have loaded in which leads to the load times. Reducing that wait time won't "break" much but you will find that if for example you have a navigation bar that visible on desktop but hidden on mobile Astrum won't be able to detect this properly and you may get some strange results.

We're looking into improving load times through caching in a future update.

Thanks
Ryan

**Comment by sethwhitaker** [comment]
Seems a bit opinionated for the pattern library to decide when something is visible or not. Wouldnt it make more sense to leave that up to the developers and their own design system? 

Maybe im not fully understanding the reasoning behind it or what actually is being hidden.

**Comment by RyanHavoc** [comment]
@sethwhitaker I think you're misunderstanding. Say for example you have a component that's visible on desktop but hidden on mobile, or vice-versa. Instead of showing an empty sample Astrum show's a message that say's "This component is hidden at this resolution.". 

To detect if the component is hidden or not it checks it's rendered height. If it's 0 it's hidden and the message is shown.

Astrum isn't forcing elements to be hidden it's just not showing a "broken" component when you hide an element through your stylesheet.

**Comment by sethwhitaker** [comment]
@RyanHavoc Ah ok, thanks for the clarification.
